[[flavour]]
name = 'arm64'
[flavour.build]
config = [
 'config',
 'arm64/config',
 'arm64/config.gardenlinux',
 'config.gardenlinux',
 'config.ima',
 'config.tdx'
]
[flavour.defs]
is_default = true
[flavour.description]
hardware = '64-bit ARMv8 machines'
[flavour.packages]
installer = true

[[flavour]]
name = 'cloud-arm64'
[flavour.build]
config = [
 'arm64/config.gardenlinux',
 'config.cloud',
 'arm64/config.cloud-arm64',
 'config.gardenlinux',
 'config.ima'
]
[flavour.defs]
is_quick = true
[flavour.description]
hardware = 'arm64 cloud'
hardware_long = 'cloud platforms supporting arm64 virtual machines'

[[flavour]]
name = 'firecracker-arm64'
[flavour.build]
config = [
 'arm64/config.gardenlinux',
 'config.cloud',
 'arm64/config.cloud-arm64',
 'config.gardenlinux',
 'config.firecracker',
 'arm64/config.firecracker'
]
[flavour.defs]
is_quick = true
[flavour.description]
hardware = 'aarch64 cloud'
hardware_long = 'cloud platforms supporting arm64 virtual machines'

[[featureset]]
name = 'none'

[build]
compiler_gnutype_compat = 'arm-linux-gnueabihf'
enable_signed = false
enable_vdso = true
kernel_file = 'arch/arm64/boot/Image'
kernel_stem = 'vmlinuz'

[relations.image]
suggests = ['systemd-boot']
