[[flavour]]
name = 'amd64'
[flavour.build]
config = [
 'amd64/config',
 'config.gardenlinux',
 'config.ima'
]
[flavour.defs]
is_default = true
[flavour.description]
hardware = '64-bit PCs'
hardware_long = 'PCs with AMD64, Intel 64 or VIA Nano processors'
[flavour.packages]
installer = true

[[flavour]]
name = 'cloud-amd64'
[flavour.build]
config = [
 'amd64/config',
 'config.cloud',
 'amd64/config.cloud-amd64',
 'config.gardenlinux',
 'config.ima'
]
[flavour.defs]
is_quick = true
[flavour.description]
hardware = 'x86-64 cloud'
hardware_long = 'cloud platforms including Amazon EC2, Microsoft Azure, and Google Compute Engine'

[[flavour]]
name = 'firecracker-amd64'
[flavour.build]
config = [
 'amd64/config',
 'config.cloud',
 'amd64/config.cloud-amd64',
 'config.gardenlinux',
 'config.firecracker',
 'amd64/config.firecracker'
]
[flavour.description]
hardware = 'x86-64 firecracker'
hardware_long = 'firecracker micro vm (https://firecracker-microvm.github.io/)'

[[featureset]]
name = 'none'

[build]
enable_signed = false
enable_vdso = true
kernel_file = 'arch/x86/boot/bzImage'
kernel_stem = 'vmlinuz'

[relations.image]
suggests = ['systemd-boot | syslinux']
